In [2]:
import pandas as pd
nba = pd.read_excel("/content/drive/MyDrive/udmy/AP005320241/Nba Teams.xlsx")
nba.head()

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country
0,Bogdan Bogdanovic,Atlanta Hawks,SouthEast,G,6'6,220.0,1992-08-18,NaN,18000000.0,RS
1,Brandon Goodwin,Atlanta Hawks,SouthEast,G,NaN,180.0,1995-10-02,Central Florida,1701593.0,US
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,Maryland,1517981.0,AO
3,Cam Reddish,Atlanta Hawks,SouthEast,F,6'8,218.0,1999-09-01,Duke,NaN,US
4,Clint Capela,Atlanta Hawks,SouthEast,C,6'10,240.0,1994-05-18,NaN,16000000.0,CH

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
nba.head(10)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country
0,Bogdan Bogdanovic,Atlanta Hawks,SouthEast,G,6'6,220.0,1992-08-18,NaN,18000000.0,RS
1,Brandon Goodwin,Atlanta Hawks,SouthEast,G,NaN,180.0,1995-10-02,Central Florida,1701593.0,US
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,Maryland,1517981.0,AO
3,Cam Reddish,Atlanta Hawks,SouthEast,F,6'8,218.0,1999-09-01,Duke,NaN,US
4,Clint Capela,Atlanta Hawks,SouthEast,C,6'10,240.0,1994-05-18,NaN,16000000.0,CH
5,Danilo Gallinari,Atlanta Hawks,SouthEast,F,6'10,233.0,1988-08-08,NaN,19500000.0,IT
6,De'Andre Hunter,Atlanta Hawks,SouthEast,F,6'7,225.0,1997-12-02,Virginia,7422000.0,US
7,John Collins,Atlanta Hawks,SouthEast,F,6'9,235.0,1997-09-23,Wake Forest,4137302.0,US
8,Kevin Huerter,Atlanta Hawks,SouthEast,G,6'7,190.0,1998-08-27,Maryland,2761920.0,US
9,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN

In [ ]:
nba.tail()

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country
493,Rui Hachimura,Washington Wizards,SouthEast,F,6'8,230.0,1998-02-08,Gonzaga,4692840.0,JP
494,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
495,Russell Westbrook,Washington Wizards,SouthEast,G,6'3,200.0,1988-11-12,UCLA,41358814.0,US
496,Thomas Bryant,Washington Wizards,SouthEast,C,6'10,248.0,1997-07-31,Indiana,8333333.0,US
497,Troy Brown Jr.,Washington Wizards,SouthEast,G-F,6'6,215.0,1999-07-28,Oregon,3372840.0,US

In [ ]:
nbaNoNull = nba.dropna()
nbaNoNull

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,Maryland,1517981.0,AO
6,De'Andre Hunter,Atlanta Hawks,SouthEast,F,6'7,225.0,1997-12-02,Virginia,7422000.0,US
7,John Collins,Atlanta Hawks,SouthEast,F,6'9,235.0,1997-09-23,Wake Forest,4137302.0,US
8,Kevin Huerter,Atlanta Hawks,SouthEast,G,6'7,190.0,1998-08-27,Maryland,2761920.0,US
10,Kris Dunn,Atlanta Hawks,SouthEast,G,6'3,205.0,1994-03-18,Providence,4767000.0,US
...,...,...,...,...,...,...,...,...,...,...
492,Robin Lopez,Washington Wizards,SouthEast,C,7'0,281.0,1988-04-01,Stanford,7300000.0,US
493,Rui Hachimura,Washington Wizards,SouthEast,F,6'8,230.0,1998-02-08,Gonzaga,4692840.0,JP
495,Russell Westbrook,Washington Wizards,SouthEast,G,6'3,200.0,1988-11-12,UCLA,41358814.0,US
496,Thomas Bryant,Washington Wizards,SouthEast,C,6'10,248.0,1997-07-31,Indiana,8333333.0,US
497,Troy Brown Jr.,Washington Wizards,SouthEast,G-F,6'6,215.0,1999-07-28,Oregon,3372840.0,US

In [ ]:
nba

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country
0,Bogdan Bogdanovic,Atlanta Hawks,SouthEast,G,6'6,220.0,1992-08-18,NaN,18000000.0,RS
1,Brandon Goodwin,Atlanta Hawks,SouthEast,G,NaN,180.0,1995-10-02,Central Florida,1701593.0,US
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,Maryland,1517981.0,AO
3,Cam Reddish,Atlanta Hawks,SouthEast,F,6'8,218.0,1999-09-01,Duke,NaN,US
4,Clint Capela,Atlanta Hawks,SouthEast,C,6'10,240.0,1994-05-18,NaN,16000000.0,CH
...,...,...,...,...,...,...,...,...,...,...
493,Rui Hachimura,Washington Wizards,SouthEast,F,6'8,230.0,1998-02-08,Gonzaga,4692840.0,JP
494,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
495,Russell Westbrook,Washington Wizards,SouthEast,G,6'3,200.0,1988-11-12,UCLA,41358814.0,US
496,Thomas Bryant,Washington Wizards,SouthEast,C,6'10,248.0,1997-07-31,Indiana,8333333.0,US
497,Troy Brown Jr.,Washington Wizards,SouthEast,G-F,6'6,215.0,1999-07-28,Oregon,3372840.0,US

In [ ]:
#nba.dropna(inplace=True)
nba.dropna()
nba

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country
0,Bogdan Bogdanovic,Atlanta Hawks,SouthEast,G,6'6,220.0,1992-08-18,NaN,18000000.0,RS
1,Brandon Goodwin,Atlanta Hawks,SouthEast,G,NaN,180.0,1995-10-02,Central Florida,1701593.0,US
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,Maryland,1517981.0,AO
3,Cam Reddish,Atlanta Hawks,SouthEast,F,6'8,218.0,1999-09-01,Duke,NaN,US
4,Clint Capela,Atlanta Hawks,SouthEast,C,6'10,240.0,1994-05-18,NaN,16000000.0,CH
...,...,...,...,...,...,...,...,...,...,...
493,Rui Hachimura,Washington Wizards,SouthEast,F,6'8,230.0,1998-02-08,Gonzaga,4692840.0,JP
494,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
495,Russell Westbrook,Washington Wizards,SouthEast,G,6'3,200.0,1988-11-12,UCLA,41358814.0,US
496,Thomas Bryant,Washington Wizards,SouthEast,C,6'10,248.0,1997-07-31,Indiana,8333333.0,US
497,Troy Brown Jr.,Washington Wizards,SouthEast,G-F,6'6,215.0,1999-07-28,Oregon,3372840.0,US

In [ ]:
nba.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 498 entries, 0 to 497
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        484 non-null    object
 1   Team        484 non-null    object
 2   Division    484 non-null    object
 3   Position    484 non-null    object
 4   Height      470 non-null    object
 5   Weight      484 non-null    float64
 6   Birth_Date  484 non-null    datetime64[ns]
 7   College     422 non-null    object
 8   Salary      434 non-null    float64
 9   Country     484 non-null    object
dtypes: datetime64[ns](1), float64(2), object(7)
memory usage: 39.0+ KB

In [ ]:
nba

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country
0,Bogdan Bogdanovic,Atlanta Hawks,SouthEast,G,6'6,220.0,1992-08-18,NaN,18000000.0,RS
1,Brandon Goodwin,Atlanta Hawks,SouthEast,G,NaN,180.0,1995-10-02,Central Florida,1701593.0,US
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,Maryland,1517981.0,AO
3,Cam Reddish,Atlanta Hawks,SouthEast,F,6'8,218.0,1999-09-01,Duke,NaN,US
4,Clint Capela,Atlanta Hawks,SouthEast,C,6'10,240.0,1994-05-18,NaN,16000000.0,CH
...,...,...,...,...,...,...,...,...,...,...
493,Rui Hachimura,Washington Wizards,SouthEast,F,6'8,230.0,1998-02-08,Gonzaga,4692840.0,JP
494,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
495,Russell Westbrook,Washington Wizards,SouthEast,G,6'3,200.0,1988-11-12,UCLA,41358814.0,US
496,Thomas Bryant,Washington Wizards,SouthEast,C,6'10,248.0,1997-07-31,Indiana,8333333.0,US
497,Troy Brown Jr.,Washington Wizards,SouthEast,G-F,6'6,215.0,1999-07-28,Oregon,3372840.0,US

In [ ]:
nba.dropna(how="all")

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country
0,Bogdan Bogdanovic,Atlanta Hawks,SouthEast,G,6'6,220.0,1992-08-18,NaN,18000000.0,RS
1,Brandon Goodwin,Atlanta Hawks,SouthEast,G,NaN,180.0,1995-10-02,Central Florida,1701593.0,US
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,Maryland,1517981.0,AO
3,Cam Reddish,Atlanta Hawks,SouthEast,F,6'8,218.0,1999-09-01,Duke,NaN,US
4,Clint Capela,Atlanta Hawks,SouthEast,C,6'10,240.0,1994-05-18,NaN,16000000.0,CH
...,...,...,...,...,...,...,...,...,...,...
492,Robin Lopez,Washington Wizards,SouthEast,C,7'0,281.0,1988-04-01,Stanford,7300000.0,US
493,Rui Hachimura,Washington Wizards,SouthEast,F,6'8,230.0,1998-02-08,Gonzaga,4692840.0,JP
495,Russell Westbrook,Washington Wizards,SouthEast,G,6'3,200.0,1988-11-12,UCLA,41358814.0,US
496,Thomas Bryant,Washington Wizards,SouthEast,C,6'10,248.0,1997-07-31,Indiana,8333333.0,US
497,Troy Brown Jr.,Washington Wizards,SouthEast,G-F,6'6,215.0,1999-07-28,Oregon,3372840.0,US

In [ ]:
nba.dropna(axis = 0)

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,Maryland,1517981.0,AO
6,De'Andre Hunter,Atlanta Hawks,SouthEast,F,6'7,225.0,1997-12-02,Virginia,7422000.0,US
7,John Collins,Atlanta Hawks,SouthEast,F,6'9,235.0,1997-09-23,Wake Forest,4137302.0,US
8,Kevin Huerter,Atlanta Hawks,SouthEast,G,6'7,190.0,1998-08-27,Maryland,2761920.0,US
10,Kris Dunn,Atlanta Hawks,SouthEast,G,6'3,205.0,1994-03-18,Providence,4767000.0,US
...,...,...,...,...,...,...,...,...,...,...
492,Robin Lopez,Washington Wizards,SouthEast,C,7'0,281.0,1988-04-01,Stanford,7300000.0,US
493,Rui Hachimura,Washington Wizards,SouthEast,F,6'8,230.0,1998-02-08,Gonzaga,4692840.0,JP
495,Russell Westbrook,Washington Wizards,SouthEast,G,6'3,200.0,1988-11-12,UCLA,41358814.0,US
496,Thomas Bryant,Washington Wizards,SouthEast,C,6'10,248.0,1997-07-31,Indiana,8333333.0,US
497,Troy Brown Jr.,Washington Wizards,SouthEast,G-F,6'6,215.0,1999-07-28,Oregon,3372840.0,US

In [ ]:
nba.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[498 rows x 0 columns]

In [ ]:
nba.dropna(subset = ["Name", "Salary", "College"])

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country
1,Brandon Goodwin,Atlanta Hawks,SouthEast,G,NaN,180.0,1995-10-02,Central Florida,1701593.0,US
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,Maryland,1517981.0,AO
6,De'Andre Hunter,Atlanta Hawks,SouthEast,F,6'7,225.0,1997-12-02,Virginia,7422000.0,US
7,John Collins,Atlanta Hawks,SouthEast,F,6'9,235.0,1997-09-23,Wake Forest,4137302.0,US
8,Kevin Huerter,Atlanta Hawks,SouthEast,G,6'7,190.0,1998-08-27,Maryland,2761920.0,US
...,...,...,...,...,...,...,...,...,...,...
492,Robin Lopez,Washington Wizards,SouthEast,C,7'0,281.0,1988-04-01,Stanford,7300000.0,US
493,Rui Hachimura,Washington Wizards,SouthEast,F,6'8,230.0,1998-02-08,Gonzaga,4692840.0,JP
495,Russell Westbrook,Washington Wizards,SouthEast,G,6'3,200.0,1988-11-12,UCLA,41358814.0,US
496,Thomas Bryant,Washington Wizards,SouthEast,C,6'10,248.0,1997-07-31,Indiana,8333333.0,US
497,Troy Brown Jr.,Washington Wizards,SouthEast,G-F,6'6,215.0,1999-07-28,Oregon,3372840.0,US