In [ ]:
import pandas as pd
nba = pd.read_excel('/content/drive/MyDrive/udmy/dataAnalisys/Nba Teams.xlsx')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
nba.head(10)

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country
0,Bogdan Bogdanovic,Atlanta Hawks,SouthEast,G,6'6,220.0,1992-08-18,NaN,18000000.0,RS
1,Brandon Goodwin,Atlanta Hawks,SouthEast,G,NaN,180.0,1995-10-02,Central Florida,1701593.0,US
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,Maryland,1517981.0,AO
3,Cam Reddish,Atlanta Hawks,SouthEast,F,6'8,218.0,1999-09-01,Duke,NaN,US
4,Clint Capela,Atlanta Hawks,SouthEast,C,6'10,240.0,1994-05-18,NaN,16000000.0,CH
5,Danilo Gallinari,Atlanta Hawks,SouthEast,F,6'10,233.0,1988-08-08,NaN,19500000.0,IT
6,De'Andre Hunter,Atlanta Hawks,SouthEast,F,6'7,225.0,1997-12-02,Virginia,7422000.0,US
7,John Collins,Atlanta Hawks,SouthEast,F,6'9,235.0,1997-09-23,Wake Forest,4137302.0,US
8,Kevin Huerter,Atlanta Hawks,SouthEast,G,6'7,190.0,1998-08-27,Maryland,2761920.0,US
9,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN

In [ ]:
nba.fillna(0)

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country
0,Bogdan Bogdanovic,Atlanta Hawks,SouthEast,G,6'6,220.0,1992-08-18 00:00:00,0,18000000.0,RS
1,Brandon Goodwin,Atlanta Hawks,SouthEast,G,0,180.0,1995-10-02 00:00:00,Central Florida,1701593.0,US
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15 00:00:00,Maryland,1517981.0,AO
3,Cam Reddish,Atlanta Hawks,SouthEast,F,6'8,218.0,1999-09-01 00:00:00,Duke,0.0,US
4,Clint Capela,Atlanta Hawks,SouthEast,C,6'10,240.0,1994-05-18 00:00:00,0,16000000.0,CH
...,...,...,...,...,...,...,...,...,...,...
493,Rui Hachimura,Washington Wizards,SouthEast,F,6'8,230.0,1998-02-08 00:00:00,Gonzaga,4692840.0,JP
494,0,0,0,0,0,0.0,0,0,0.0,0
495,Russell Westbrook,Washington Wizards,SouthEast,G,6'3,200.0,1988-11-12 00:00:00,UCLA,41358814.0,US
496,Thomas Bryant,Washington Wizards,SouthEast,C,6'10,248.0,1997-07-31 00:00:00,Indiana,8333333.0,US
497,Troy Brown Jr.,Washington Wizards,SouthEast,G-F,6'6,215.0,1999-07-28 00:00:00,Oregon,3372840.0,US

In [ ]:
nba[["College"]].fillna(0, inplace = True)# Reemplaza los valores nulos de la columna "College" por 0
nba

<ipython-input-18-f09fa7061776>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nba[["College"]].fillna(0, inplace = True)

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country
0,Bogdan Bogdanovic,Atlanta Hawks,SouthEast,G,6'6,220.0,1992-08-18,0,18000000.0,RS
1,Brandon Goodwin,Atlanta Hawks,SouthEast,G,NaN,180.0,1995-10-02,Central Florida,1701593.0,US
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,Maryland,1517981.0,AO
3,Cam Reddish,Atlanta Hawks,SouthEast,F,6'8,218.0,1999-09-01,Duke,0.0,US
4,Clint Capela,Atlanta Hawks,SouthEast,C,6'10,240.0,1994-05-18,0,16000000.0,CH
...,...,...,...,...,...,...,...,...,...,...
493,Rui Hachimura,Washington Wizards,SouthEast,F,6'8,230.0,1998-02-08,Gonzaga,4692840.0,JP
494,NaN,NaN,NaN,NaN,NaN,NaN,NaT,0,0.0,NaN
495,Russell Westbrook,Washington Wizards,SouthEast,G,6'3,200.0,1988-11-12,UCLA,41358814.0,US
496,Thomas Bryant,Washington Wizards,SouthEast,C,6'10,248.0,1997-07-31,Indiana,8333333.0,US
497,Troy Brown Jr.,Washington Wizards,SouthEast,G-F,6'6,215.0,1999-07-28,Oregon,3372840.0,US

In [ ]:
nba["Name"].fillna("Missing name", inplace = True)
# Reemplaza los valores nulos de la columna "Name" por "Missing name"
nba

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country
0,Bogdan Bogdanovic,Atlanta Hawks,SouthEast,G,6'6,220.0,1992-08-18,NaN,18000000.0,RS
1,Brandon Goodwin,Atlanta Hawks,SouthEast,G,NaN,180.0,1995-10-02,Central Florida,1701593.0,US
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,Maryland,1517981.0,AO
3,Cam Reddish,Atlanta Hawks,SouthEast,F,6'8,218.0,1999-09-01,Duke,0.0,US
4,Clint Capela,Atlanta Hawks,SouthEast,C,6'10,240.0,1994-05-18,NaN,16000000.0,CH
...,...,...,...,...,...,...,...,...,...,...
493,Rui Hachimura,Washington Wizards,SouthEast,F,6'8,230.0,1998-02-08,Gonzaga,4692840.0,JP
494,Missing name,NaN,NaN,NaN,NaN,NaN,NaT,NaN,0.0,NaN
495,Russell Westbrook,Washington Wizards,SouthEast,G,6'3,200.0,1988-11-12,UCLA,41358814.0,US
496,Thomas Bryant,Washington Wizards,SouthEast,C,6'10,248.0,1997-07-31,Indiana,8333333.0,US
497,Troy Brown Jr.,Washington Wizards,SouthEast,G-F,6'6,215.0,1999-07-28,Oregon,3372840.0,US