In [ ]:
import pandas as pd
emp = pd.read_csv("/content/drive/MyDrive/udmy/dataAnalisys/Employee.csv")
emp.head()

                    name   department          position       salary
0     JEDIDIAH, PALLAS O      FINANCE  PYTHON DEVELOPER  $108,156.28
1  FLORETTE, JODLOWSKI R    MARKETING          DIRECTOR   $85,000.00
2       KIZZIE, PAULUS D  PROCUREMENT          DIRECTOR   $85,000.00
3      ENNIS, MACQUIST N        SALES      DATA ANALYST   $76,715.61
4       VAIL, HONATSCH R       DESIGN         DEVELOPER  $117,247.37

In [ ]:
emp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1010 entries, 0 to 1009
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        1010 non-null   object
 1   department  1010 non-null   object
 2   position    1010 non-null   object
 3   salary      1010 non-null   object
dtypes: object(4)
memory usage: 31.7+ KB

In [ ]:
emp.nunique()

name          1010
department      11
position        26
salary         947
dtype: int64

In [ ]:
emp[["department", "position"]] = emp[["department", "position"]].astype("category")# Cambia los tipos de datos de las columnas "department" y "position" a categoría

In [ ]:
emp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1010 entries, 0 to 1009
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        1010 non-null   object
 1   department  1010 non-null   category
 2   position    1010 non-null   category
 3   salary      1010 non-null   object
dtypes: category(2), object(2)
memory usage: 19.5+ KB

In [ ]:
"happy".upper()
"PYTHON".lower()

'python'

In [ ]:
emp["name"]
emp["name"].str.lower().str.title()# Convierte los nombres a formato título (Primera letra mayúscula, resto minúsculas)

0          Jedidiah, Pallas O
1       Florette, Jodlowski R
2            Kizzie, Paulus D
3           Ennis, Macquist N
4            Vail, Honatsch R
                ...
1005           James, Bolam M
1006       Carlynn, Eddolls A
1007        Rozelle, Foston S
1008           Alard, Ekins J
1009           Aloin, Reade C
Name: name, Length: 1010, dtype: object