In [ ]:
import pandas as pd
#nba = pd.read_excel("Nba Teams.xlsx")
nba = pd.read_excel("/content/drive/MyDrive/udmy/dataAnalisys/Nba Teams.xlsx").dropna(how = "all")
nba

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country
0,Bogdan Bogdanovic,Atlanta Hawks,SouthEast,G,6'6,220.0,1992-08-18,NaN,18000000.0,RS
1,Brandon Goodwin,Atlanta Hawks,SouthEast,G,NaN,180.0,1995-10-02,Central Florida,1701593.0,US
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,Maryland,1517981.0,AO
3,Cam Reddish,Atlanta Hawks,SouthEast,F,6'8,218.0,1999-09-01,Duke,NaN,US
4,Clint Capela,Atlanta Hawks,SouthEast,C,6'10,240.0,1994-05-18,NaN,16000000.0,CH
...,...,...,...,...,...,...,...,...,...,...
492,Robin Lopez,Washington Wizards,SouthEast,C,7'0,281.0,1988-04-01,Stanford,7300000.0,US
493,Rui Hachimura,Washington Wizards,SouthEast,F,6'8,230.0,1998-02-08,Gonzaga,4692840.0,JP
495,Russell Westbrook,Washington Wizards,SouthEast,G,6'3,200.0,1988-11-12,UCLA,41358814.0,US
496,Thomas Bryant,Washington Wizards,SouthEast,C,6'10,248.0,1997-07-31,Indiana,8333333.0,US
497,Troy Brown Jr.,Washington Wizards,SouthEast,G-F,6'6,215.0,1999-07-28,Oregon,3372840.0,US

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
nba.info()

<class 'pandas.core.frame.DataFrame'>
Index: 484 entries, 0 to 497
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        484 non-null    object
 1   Team        484 non-null    object
 2   Division    484 non-null    object
 3   Position    484 non-null    object
 4   Height      470 non-null    object
 5   Weight      484 non-null    float64
 6   Birth_Date  484 non-null    datetime64[ns]
 7   College     422 non-null    object
 8   Salary      434 non-null    float64
 9   Country     484 non-null    object
dtypes: datetime64[ns](1), float64(2), object(7)
memory usage: 41.6+ KB

In [ ]:
nba["Height"].fillna("Missing")

0          6'6
1      Missing
2          6'9
3          6'8
4         6'10
        ...
492        7'0
493        6'8
495        6'3
496       6'10
497        6'6
Name: Height, Length: 484, dtype: object