In [ ]:
import pandas as pd
nba = pd.read_excel('/content/drive/MyDrive/udmy/dataAnalisys/Nba Teams.xlsx')
nba.head()

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country
0,Bogdan Bogdanovic,Atlanta Hawks,SouthEast,G,6'6,220.0,1992-08-18,NaN,18000000.0,RS
1,Brandon Goodwin,Atlanta Hawks,SouthEast,G,NaN,180.0,1995-10-02,Central Florida,1701593.0,US
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,Maryland,1517981.0,AO
3,Cam Reddish,Atlanta Hawks,SouthEast,F,6'8,218.0,1999-09-01,Duke,NaN,US
4,Clint Capela,Atlanta Hawks,SouthEast,C,6'10,240.0,1994-05-18,NaN,16000000.0,CH

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
nba["Team"].value_counts()# Cuenta cuántas veces aparece cada equipo en la columna "Team"

Team
Miami Heat                 18
Boston Celtics             17
Brooklyn Nets              17
Toronto Raptors            17
Cleveland Cavaliers        17
Dallas Mavericks           17
Philadelphia 76ers         17
Detroit Pistons            17
Oklahoma City Thunder      17
Indiana Pacers             17
New York Knicks            17
Minnesota Timberwolves     17
Milwaukee Bucks            17
Sacramento Kings           16
Orlando Magic              16
Atlanta Hawks              16
Memphis Grizzlies          16
Houston Rockets            16
Golden State Warriors      16
Charlotte Hornets          16
Washington Wizards         16
Los Angeles Lakers         15
New Orleans Pelicans       15
Los Angeles Clippers       15
Denver Nuggets             15
Phoenix Suns               15
Chicago Bulls              15
San Antonio Spurs          15
Utah Jazz                  15
Portland Trail Blazers     14
Name: count, dtype: int64

In [ ]:
#nba["Division"].value_counts()
nba["Division"].value_counts(ascending = True)# Cuenta cuántas veces aparece cada división, de menor a mayor frecuencia

Division
Pacific      77
NorthWest    78
SouthWest    79
SouthEast    82
Central      83
Atlantic     85
Name: count, dtype: int64